# Generated by Django 5.1.dev20231230132810 on 2024-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "object_id",
                    models.CharField(
                        default="",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键",
                    ),
                ),
                (
                    "show_id",
                    models.CharField(default="", max_length=50, verbose_name="显示ID"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="用户名"
                    ),
                ),
                ("message", models.CharField(max_length=100, verbose_name="留言信息")),
            ],
            options={
                "verbose_name_plural": "用户留言信息",
                "db_table": "user_message",
                "ordering": ("-object_id",),
            },
        ),
    ]
