# Generated by Django 5.1.dev20231230132810 on 2024-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_rating_alter_usermessage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermessage",
            name="rating",
        ),
        migrations.AlterModelOptions(
            name="usermessage",
            options={"ordering": ("-object_id",), "verbose_name_plural": "用户留言信息"},
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="message",
            field=models.CharField(max_length=100, verbose_name="留言信息"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="用户名"
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="object_id",
            field=models.CharField(
                default="",
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="主键",
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="show_id",
            field=models.CharField(default="", max_length=50, verbose_name="显示ID"),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
