# Generated by Django 5.1.dev20231230132810 on 2024-01-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "message",
            "0003_remove_usermessage_rating_alter_usermessage_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating_value",
                    models.DecimalField(
                        choices=[
                            (0, "0 Star"),
                            (0.5, "0.5 Star"),
                            (1, "1 Star"),
                            (1.5, "1.5 Stars"),
                            (2, "2 Stars"),
                            (2.5, "2.5 Stars"),
                            (3, "3 Stars"),
                            (3.5, "3.5 Stars"),
                            (4, "4 Stars"),
                            (4.5, "4.5 Stars"),
                            (5, "5 Stars"),
                        ],
                        decimal_places=1,
                        help_text="Select the rating value.",
                        max_digits=2,
                        verbose_name="Rating Value",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.AlterModelOptions(
            name="usermessage",
            options={"ordering": ("-object_id",)},
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="message",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="object_id",
            field=models.CharField(
                default="", max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="show_id",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="usermessage",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="message.rating",
            ),
        ),
    ]
