# Generated by Django 5.1.dev20231230132810 on 2024-01-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0006_rating_alter_usermessage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={},
        ),
        migrations.RemoveField(
            model_name="rating",
            name="rating_value",
        ),
        migrations.AddField(
            model_name="rating",
            name="five",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="four",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="one",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="three",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="two",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.rating",
            ),
        ),
    ]
