# Generated by Django 5.0 on 2024-01-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix',
            name='type',
            field=models.CharField(choices=[('TV Show', 'TV Show'), ('Movie', 'Movie')], max_length=10),
        ),
    ]
