# Generated by Django 5.0 on 2024-01-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_alter_netflix_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='average_score',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='score_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
