# Generated by Django 5.0 on 2024-01-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_alter_form_average_score_alter_form_score_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='cast',
            field=models.CharField(default='NAME', max_length=30),
        ),
    ]
