# Generated by Django 5.0 on 2024-01-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_form_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('average_score', models.FloatField()),
            ],
        ),
    ]
